<?php

return array (
  'core\\Group\\Contracts\\Config\\Config' => 'core/Group/Contracts/Config/Config.php',
  'core\\Group\\Contracts\\Container\\Container' => 'core/Group/Contracts/Container/Container.php',
  'core\\Group\\Contracts\\Exceptions\\Exception' => 'core/Group/Contracts/Exceptions/Exception.php',
  'core\\Group\\Contracts\\Http\\Request' => 'core/Group/Contracts/Http/Request.php',
  'core\\Group\\Contracts\\Http\\Response' => 'core/Group/Contracts/Http/Response.php',
  'core\\Group\\Contracts\\Routing\\Route' => 'core/Group/Contracts/Routing/Route.php',
  'core\\Group\\Contracts\\Routing\\Router' => 'core/Group/Contracts/Routing/Router.php',

  'core\\Group\\Common\\ArrayToolkit' => 'core/Group/Common/ArrayToolkit.php',
  'core\\Group\\Config\\Config' => 'core/Group/Config/Config.php',
  'core\\Group\\Container\\Container' => 'core/Group/Container/Container.php',
  'core\\Group\\Controller\\BaseController' => 'core/Group/Controller/BaseController.php',
  'core\\Group\\Controller\\Controller' => 'core/Group/Controller/Controller.php',
  'core\\Group\\Cookie\\CookieServiceProvider' => 'core/Group/Cookie/CookieServiceProvider.php',
  'core\\Group\\Dao\\Dao' => 'core/Group/Dao/Dao.php',
  'core\\Group\\Exceptions\\NotFoundException' => 'core/Group/Exceptions/NotFoundException.php',
  'core\\Group\\Handlers\\AliasLoaderHandler' => 'core/Group/Handlers/AliasLoaderHandler.php',
  'core\\Group\\Http\\Request' => 'core/Group/Http/Request.php',
  'core\\Group\\Http\\Response' => 'core/Group/Http/Response.php',
  'core\\Group\\Kernal' => 'core/Group/Kernal.php',
  'core\\Group\\Log\\Log' => 'core/Group/Log/Log.php',
  'core\\Group\\Redis\\RedisServiceProvider' => 'core/Group/Redis/RedisServiceProvider.php',
  'core\\Group\\Routing\\Route' => 'core/Group/Routing/Route.php',
  'core\\Group\\Routing\\Router' => 'core/Group/Routing/Router.php',
  'core\\Group\\Services\\Service' => 'core/Group/Services/Service.php',
  'core\\Group\\Session\\SessionServiceProvider' => 'core/Group/Session/SessionServiceProvider.php',

  'src\\Services\\Group\\Dao\\GroupDao' => 'src/Services/Group/Dao/GroupDao.php',
  'src\\Services\\Group\\Dao\\Impl\\GroupDaoImpl' => 'src/Services/Group/Dao/Impl/GroupDaoImpl.php',
  'src\\Services\\Group\\GroupService' => 'src/Services/Group/GroupService.php',
  'src\\Services\\Group\\Impl\\GroupServiceImpl' => 'src/Services/Group/Impl/GroupServiceImpl.php',
);