#!/usr/bin/env php
<?php

use Group\Async\Async;
use Group\App\App;

$loader = require __DIR__.'/../vendor/autoload.php';

$loader->setUseIncludePath(true);

define('__ROOT__', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "../");

$app = new App();
$app -> initSelf();
$provider = new Group\Cache\FileCacheServiceProvider($app::getInstance());
$provider -> register();

$async = new Async($argv);
$async -> run();
