#!/usr/bin/env php
<?php

use Group\Async\Async;
use Group\App\App;

$loader = require __DIR__.'/../vendor/autoload.php';

$loader->setUseIncludePath(true);

define('__ROOT__', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "../");

$app = App::getInstance();
$app -> doBootstrap($loader);
$app -> registerServices();
$app -> singleton('container') -> setAppPath(__ROOT__);

$async = new Async($argv);
$async -> run();
