#!/usr/bin/env php
<?php

use Group\Console\Console;
use Group\App\App;

$loader = require __DIR__.'/../vendor/autoload.php';

define('__ROOT__', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "../");

$loader->setUseIncludePath(true);

$console = new Console($argv);

$app = new App();

$app -> initSelf();

$app -> registerServices();

$console -> run();