#!/usr/bin/env php
<?php

use Group\Cron\Cron;
use Group\App\App;

$loader = require __DIR__.'/../vendor/autoload.php';

$loader->setUseIncludePath(true);

define('__ROOT__', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "../");

$app = new App();
$app -> initSelf();
$app -> doBootstrap($loader);
$app -> registerServices();
$app -> singleton('container') -> setAppPath(__ROOT__);

$cron = new Cron($argv, $loader);
$cron -> run();

