#!/usr/bin/env php
<?php

use Group\Queue\MessageQueue;
use Group\App\App;

$loader = require __DIR__.'/../vendor/autoload.php';

$loader->setUseIncludePath(true);

define('__ROOT__', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "../");

$queue = new MessageQueue($argv, $loader);

$app = new App();

$app -> initSelf();

$app -> doBootstrap($loader);

$app -> registerServices();

$queue -> run();